name: Horse_Inspector
main: com.anomalytea.HorseInspector.HorseInspector
version: 1.2.1
api-version: 1.14
commands:
  horseinspector:
    description: Reload the Horse Inspector configuration file without restarting the server.
    usage: /horseinspector reload
permissions:
  horseinspector.use:
    default: true
  horseinspector.reload:
    default: op
